# Un seul gestionnaire de connexion possible sur cette distribution : SDDM
# (déjà utilisé en live, cf. airootfs/etc/sddm.conf.d/).
---
displaymanagers:
    - sddm

basicSetup: false

sysconfigSetup: false
