# Active les services nécessaires sur le système installé.
# "mandatory: true" fait échouer l'installation si le service n'existe pas
# sur la cible (utile pour détecter un paquet manquant dans packages.x86_64).
---
services:
    - name: "NetworkManager"
      mandatory: true
    - name: "sddm"
      mandatory: true
    - name: "sssd"
      mandatory: true
    - name: "chronyd"
      mandatory: true

targets: []

disable:
    - name: "pacman-init"
      mandatory: false
    - name: "choose-mirror"
      mandatory: false

disable-targets: []

mask: []
