# Instance "fixmkinitcpio" du module Calamares built-in "shellprocess".
# Voir usr/local/bin/fix-target-mkinitcpio.sh pour le détail du pourquoi.
---
dontChroot: false
timeout: 60
verbose: true
script: "/usr/local/bin/fix-target-mkinitcpio.sh"

i18n:
    name: "Fixing initramfs configuration for the installed system"
